"""Add file_name column to Video table

Revision ID: a09a288718ac
Revises: 4fb209067963
Create Date: 2024-02-17 12:33:51.410524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09a288718ac'
down_revision = '4fb209067963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shares', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tiktok_subscribers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instagram_followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('youtube_subscribers', sa.Integer(), nullable=True))
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('youtube_subscribers')
        batch_op.drop_column('instagram_followers')
        batch_op.drop_column('tiktok_subscribers')
        batch_op.drop_column('shares')
        batch_op.drop_column('comments')
        batch_op.drop_column('views')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
