name: Tik Tok Video Upload

on:
  schedule:
    - cron: ''0 2 * * *'  # Runs at 2 AM UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Decode and save cookies
      run: |
        echo ${{ secrets.COOKIES_BASE64 }} | base64 -d > cookies.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python main.py
